apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptive-interface
  labels:
    app: adaptive-interface
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adaptive-interface
  template:
    metadata:
      labels:
        app: adaptive-interface
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "adaptive-interface"
        dapr.io/app-port: "9150"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: adaptive-interface
        image: adaptive-interface:latest
        ports:
        - containerPort: 9150
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        - name: OPENAI_MODEL
          value: "gpt-4.1-nano"
        - name: LITERAL_DISABLE
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9150
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9150
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: adaptive-interface-service
spec:
  selector:
    app: adaptive-interface
  ports:
  - port: 80
    targetPort: 9150
    name: http
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # Replace with: echo -n "your-api-key" | base64
  api-key: ""