repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: custom-secret-scan
        name: Custom Secret Scanner
        entry: scripts/scan-secrets.sh
        language: script
        pass_filenames: false
        always_run: true
