version: '3.8'

services:
  # Redis for Dapr pub/sub
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - dapr-network

  # Zipkin for distributed tracing
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - dapr-network

  # Dapr placement service
  dapr-placement:
    image: daprio/dapr:latest
    command: ["./placement", "-port", "50006", "-log-level", "debug"]
    ports:
      - "50006:50006"
    networks:
      - dapr-network

  # Admin Agent Application
  admin-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "3500:3500"  # Dapr HTTP
      - "50001:50001"  # Dapr gRPC
      - "9090:9090"  # Metrics
    environment:
      - DATABASE_URL=postgresql+asyncpg://username:password@host:5432/compliance_sentinel
      - DEBUG=true
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001
    volumes:
      - ./components:/app/components
      - ./dapr.yaml:/app/dapr.yaml
      - ./uploads:/app/uploads
    depends_on:
      - redis
      - zipkin
      - dapr-placement
    networks:
      - dapr-network

  # Dapr sidecar for admin-agent
  admin-agent-dapr:
    image: daprio/daprd:latest
    command: [
      "./daprd",
      "-app-id", "admin-agent",
      "-app-port", "8000",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-components-path", "/components",
      "-config", "/dapr.yaml",
      "-log-level", "info",
      "-enable-profiling",
      "-enable-metrics",
      "-metrics-port", "9090",
      "-placement-host-address", "dapr-placement:50006"
    ]
    volumes:
      - ./components:/components
      - ./dapr.yaml:/dapr.yaml
    depends_on:
      - admin-agent
      - dapr-placement
    network_mode: "service:admin-agent"

volumes:
  redis_data:

networks:
  dapr-network:
    driver: bridge
