---
apiVersion: v1
kind: Namespace
metadata:
  name: compliance-sentinel
  labels:
    name: compliance-sentinel
    app.kubernetes.io/name: compliance-sentinel

---
# OpenAI API Key Secret
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: compliance-sentinel
type: Opaque
data:
  # Base64 encoded OpenAI API key
  # Replace with: echo -n "your-actual-openai-api-key" | base64
  api-key: c2stc3ZjYWNjdC04UlVja212Q1h0UXV4clJhRk5tUFJtb0M3X3FCcm5aMEJqMTBTbkJUYjFEZlZYVFVDOVY4NEp4Z1VfYXRvd1JXQm50bGVaZ3cxVDNCbGJrRkpnc3NXbjdyWXRzVW5vclZFVlV4Y0drNURYcm9IY0pJbEZVU1kxY01HQm1BVUdCS3gtaFlmczF1ZDlJSHZjeWRqc3BramROOFlB

---
# Redis Configuration Secret (for Dapr state and pub/sub)
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: compliance-sentinel
type: Opaque
data:
  # Base64 encoded Redis connection info
  redis-host: cmVkaXMtc2VydmljZQ==  # redis-service
  redis-port: NjM3OQ==  # 6379
  redis-password: ""  # empty for no password
